apiVersion: apps/v1
kind: Deployment
metadata:
  name: avif-converter
  namespace: webapps
  labels:
    app: avif-converter
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: avif-converter
  template:
    metadata:
      labels:
        app: avif-converter
    spec:
      containers:
      - name: avif-converter
        image: ghcr.io/ekskog/avif-converter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 3
