apiVersion: v1
kind: Service
metadata:
  name: avif-converter-service
  namespace: photovault
  labels:
    app: avif-converter
spec:
  selector:
    app: avif-converter
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: LoadBalancer
